Improved error handling in move_vps scripts

diff --git a/statemachines/move_vps/create_managed b/statemachines/move_vps/create_managed
--- a/statemachines/move_vps/create_managed
+++ b/statemachines/move_vps/create_managed
@@ -1,7 +1,7 @@
 #!/bin/sh
 DIR=`dirname $0`
 . $DIR/lib/json
-. /etc/restatemachine/restatemachine-pack.conf 
+. /etc/restatemachine/restatemachine-pack.conf
 . /etc/restatemachine/shell_helpers.inc
 
 INPUT=`cat`
@@ -13,44 +13,44 @@ SITENAME=`Json "$INPUT" "SiteName"`
 IP=`Json "$INPUT" "FloatingIP"`
 
 Error () {
-        echo -n $INPUT
+        echo -n "$INPUT"
         restatemachine_transition_to "wait_for_vps"
         restatemachine_transition_after_seconds 10
         restatemachine_status_message "$1"
-        exit 0 
+        exit 0
 }
 
-CSBASE=`atomia service list --account $ACCOUNT | jgrep name=CsBase -s logical_id 2> /dev/null`
-if [ "$?" != "0" ]; then
-        Error "Could not get CsCloud service"
+CSBASE=`atomia service list --account $ACCOUNT 2> /dev/null | jgrep name=CsBase -s logical_id 2> /dev/null`
+if [ "$?" != "0" ] || [ -z "$CSBASE" ]; then
+        Error "Could not get CsBase service"
 fi
 
 ROOTFOLDER=`atomia service list --account $ACCOUNT --path '[{"CsBase" : "'$CSBASE'"} ]' 2> /dev/null | jgrep name=RootFolder 2> /dev/null`
-ROOTFOLDERID=`echo -n "$ROOTFOLDER" | jgrep -s logical_id 2> /dev/null` 
-FOLDERPATH=`echo -n "$ROOTFOLDER" | grep FolderPath -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null` 
-FOLDERNAME=`echo -n "$ROOTFOLDER" | grep Name -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null` 
+ROOTFOLDERID=`echo -n "$ROOTFOLDER" | jgrep -s logical_id 2> /dev/null`
+FOLDERPATH=`echo -n "$ROOTFOLDER" | grep FolderPath -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null`
+FOLDERNAME=`echo -n "$ROOTFOLDER" | grep Name -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null`
 
 # Do archive operation
 ARCHIVEARG='{"archivepath":"'$FOLDERPATH'/'$FOLDERNAME'/'$SITENAME'.tar.gz","flags":"cvzf","permissions":"700","archivetype":"tar","operationUrl":"'$FOLDERPATH'/'$FOLDERNAME'/'$SITENAME'/public_html"}'
 ARCHIVEOP=`atomia service operation --account $ACCOUNT --service $ROOTFOLDERID --operation "ArchiveFolder" --arg $ARCHIVEARG 2> /dev/null`
-if [ "$?" != "0" ]; then 
-	Error "Could not archive folder" 
+if [ "$?" != "0" ]; then
+	Error "Could not archive folder"
 fi
 
 # Get content of archive
 SITECONTENT=`atomia service operation --account $ACCOUNT --service $ROOTFOLDERID --operation "GetFileContent" --arg "$FOLDERPATH/$FOLDERNAME/$SITENAME.tar.gz" 2> /dev/null`
-if [ "$?" != "0" ]; then 
-	Error "Could not get content of archive" 
+if [ "$?" != "0" ]; then
+	Error "Could not get content of archive"
 fi
 
 # There might be cases where CsVPSManagedItems does not exist for example on brand new VPSs we need to take care of this
 MANAGEDITEMS=`atomia service list --account $ACCOUNT --path '[{"CsCloud" : "'$CSCLOUD'"}, {"CsInstances" : "'$CSINSTANCES'"}, {"CsVPSInstance" : "'$VPSID'"}]' 2> /dev/null | jgrep name=CsVPSManagedItems -s logical_id 2> /dev/null`
 if [ "$MANAGEDITEMS" = "" ]; then
-	MANAGEDITEMS=`atomia service add --account $ACCOUNT --parent "$VPSID" --servicedata '{ "name" : "CsVPSManagedItems", "properties" : { "IpAddress" : "'$IP'" }}' | jgrep name=CsVPSManagedItems -s logical_id 2> /dev/null`
+	MANAGEDITEMS=`atomia service add --account $ACCOUNT --parent "$VPSID" --servicedata '{ "name" : "CsVPSManagedItems", "properties" : { "IpAddress" : "'$IP'" }}' 2> /dev/null | jgrep name=CsVPSManagedItems -s logical_id 2> /dev/null`
 fi
 MANAGEDITEM=`atomia service list --account $ACCOUNT --path '[{"CsCloud" : "'$CSCLOUD'"}, {"CsInstances" : "'$CSINSTANCES'"}, {"CsVPSInstance" : "'$VPSID'"}, {"CsVPSManagedItems" : "'$MANAGEDITEMS'"}]' | jgrep name=CsVPSManagedItem 2> /dev/null | grep ItemName -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// | grep $SITENAME | wc -l 2> /dev/null`
 if [ $MANAGEDITEM -eq 0 ]; then
-	ADDITEMSERVICE=`atomia service add --account $ACCOUNT --parent "$MANAGEDITEMS" --servicedata '{ "name" : "CsVPSManagedItem", "properties" : { "SkipDNS" : "true", "ItemName" : "'$SITENAME'", "ItemType" : "ApacheWebsite", "ItemMetaData" : "{\"ArchiveType\":\"tar.gz\",\"InitialWebsiteContent\":\"'$SITECONTENT'\"}" }}' 2> /dev/null ` 
+	ADDITEMSERVICE=`atomia service add --account $ACCOUNT --parent "$MANAGEDITEMS" --servicedata '{ "name" : "CsVPSManagedItem", "properties" : { "SkipDNS" : "true", "ItemName" : "'$SITENAME'", "ItemType" : "ApacheWebsite", "ItemMetaData" : "{\"ArchiveType\":\"tar.gz\",\"InitialWebsiteContent\":\"'$SITECONTENT'\"}" }}' 2> /dev/null `
 	if [ "$?" != "0" ]; then
 	        Error "Could not add managed service"
 	fi
@@ -83,7 +83,7 @@ if [ "$MIGRATIONSTATUS" != "pending" ]; then
 	fi
 fi
 
-INPUT=`echo -n $INPUT | sed  '$s/}/, "CsLinuxWebsiteId" : "'$CSWEBSITEID'", "ManagedServiceId" : "'$MANAGEDSERVICEID'" }/'`
+INPUT=`echo -n "$INPUT" | sed  '$s/}/, "CsLinuxWebsiteId" : "'$CSWEBSITEID'", "ManagedServiceId" : "'$MANAGEDSERVICEID'" }/'`
 echo -n "$INPUT"
 restatemachine_transition_to "wait_for_acceptance"
 restatemachine_transition_after_seconds "0"
diff --git a/statemachines/move_vps/delete_website b/statemachines/move_vps/delete_website
--- a/statemachines/move_vps/delete_website
+++ b/statemachines/move_vps/delete_website
@@ -1,7 +1,7 @@
 #!/bin/sh
 DIR=`dirname $0`
 . $DIR/lib/json
-. /etc/restatemachine/restatemachine-pack.conf 
+. /etc/restatemachine/restatemachine-pack.conf
 . /etc/restatemachine/shell_helpers.inc
 
 INPUT=`cat`
@@ -15,11 +15,11 @@ CSLINUXWEBSITEID=`Json "$INPUT" "CsLinuxWebsiteId"`
 MANAGEDSERVICEID=`Json "$INPUT" "ManagedServiceId"`
 
 Error () {
-        echo -n $INPUT
+        echo -n "$INPUT"
         restatemachine_transition_to "delete_website"
-        restatemachine_transition_after_seconds 120 
+        restatemachine_transition_after_seconds 120
         restatemachine_status_message "$1"
-        exit 0 
+        exit 0
 }
 
 CSWEBSITE=`atomia service show --account $ACCOUNT --service "$CSLINUXWEBSITEID" 2> /dev/null`
@@ -30,34 +30,33 @@ if [ "$MIGRATIONSTATUS" != "wait_dns" ]; then
         restatemachine_transition_to "revert_migration"
         restatemachine_transition_after_seconds 0
         restatemachine_status_message "Wrong migration status, reverting"
-        exit 0 
+        exit 0
 fi
 
 DIG=`dig A $SITENAME @8.8.8.8 | grep "$IP" | wc -l`
 #if [ $DIG -eq 0 ]; then
-	# DNS not ok 
+	# DNS not ok
 #	Error "DNS not ok yet"
 #fi
 
 # Backup all files
 ROOTFOLDER=`atomia service list --account $ACCOUNT --path '[{"CsBase" : "'$CSBASE'"} ]' 2> /dev/null| jgrep name=RootFolder 2> /dev/null`
-ROOTFOLDERID=`echo -n "$ROOTFOLDER" | jgrep -s logical_id` 
-FOLDERPATH=`echo -n "$ROOTFOLDER" | grep FolderPath -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null` 
-FOLDERNAME=`echo -n "$ROOTFOLDER" | grep Name -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null` 
+ROOTFOLDERID=`echo -n "$ROOTFOLDER" | jgrep -s logical_id`
+FOLDERPATH=`echo -n "$ROOTFOLDER" | grep FolderPath -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null`
+FOLDERNAME=`echo -n "$ROOTFOLDER" | grep Name -C 5 | grep -Poz '\{([^}]+)\}' | grep prop_string_value | awk '{ print $2}' | sed s/\"//g | sed s/\,// 2> /dev/null`
 ARCHIVEARG='{"archivepath":"'$FOLDERPATH'/'$FOLDERNAME'/'$SITENAME'.tar.gz","flags":"cvzf","permissions":"700","archivetype":"tar","operationUrl":"'$FOLDERPATH'/'$FOLDERNAME'/'$SITENAME'"}'
 ARCHIVEOP=`atomia service operation --account $ACCOUNT --service $ROOTFOLDERID --operation "ArchiveFolder" --arg $ARCHIVEARG 2> /dev/null`
-if [ "$?" != "0" ]; then 
-	Error "Could not archive folder" 
+if [ "$?" != "0" ]; then
+	Error "Could not archive folder"
 fi
 
 # Delete website
-SWITCH=`atomia service switch --account $ACCOUNT --service "$CSLINUXWEBSITEID" --newservice "CsDomainNoWebsite" --servicedata '{ "properties" : { "Domain" : "'$SITENAME'", "DnsZone" : "'$SITENAME'", "DomainPrefix": "", "InitEmail" : "", "ManagedBy": "'$MANAGEDSERVICEID'" }}'`
-if [ "$?" != "0" ]; then 
-	Error "Could not delete website" 
+SWITCH=`atomia service switch --account $ACCOUNT --service "$CSLINUXWEBSITEID" --newservice "CsDomainNoWebsite" --servicedata '{ "properties" : { "Domain" : "'$SITENAME'", "DnsZone" : "'$SITENAME'", "DomainPrefix": "", "InitEmail" : "", "ManagedBy": "'$MANAGEDSERVICEID'" }}' 2> /dev/null`
+if [ "$?" != "0" ]; then
+	Error "Could not delete website"
 fi
 
 restatemachine_transition_to "stop"
 restatemachine_transition_after_seconds 0
 restatemachine_status_message "Migration completed"
 exit 0
-
diff --git a/statemachines/move_vps/revert_migration b/statemachines/move_vps/revert_migration
--- a/statemachines/move_vps/revert_migration
+++ b/statemachines/move_vps/revert_migration
@@ -1,7 +1,7 @@
 #!/bin/sh
 DIR=`dirname $0`
 . $DIR/lib/json
-. /etc/restatemachine/restatemachine-pack.conf 
+. /etc/restatemachine/restatemachine-pack.conf
 . /etc/restatemachine/shell_helpers.inc
 
 INPUT=`cat`
@@ -14,19 +14,19 @@ IP=`Json "$INPUT" "FloatingIP"`
 CSLINUXWEBSITEID=`Json "$INPUT" "CsLinuxWebsiteId"`
 
 Error () {
-        echo -n $INPUT
+        echo -n "$INPUT"
         restatemachine_transition_to "revert_migration"
         restatemachine_transition_after_seconds 3600
         restatemachine_status_message "$1"
-        exit 0 
+        exit 0
 }
 
 # Delete managed item
 MANAGEDITEMS=`atomia service list --account $ACCOUNT --path '[{"CsCloud" : "'$CSCLOUD'"}, {"CsInstances" : "'$CSINSTANCES'"}, {"CsVPSInstance" : "'$VPSID'"}]' 2> /dev/null | jgrep name=CsVPSManagedItems -s logical_id 2> /dev/null`
 MANAGEDITEMID=`atomia service show --account $ACCOUNT --path '[{"CsCloud" : "'$CSCLOUD'"}, {"CsInstances" : "'$CSINSTANCES'"}, {"CsVPSInstance" : "'$VPSID'"}, {"CsVPSManagedItems" : "'$MANAGEDITEMS'"}, {"CsVPSManagedItem" : {"ItemName":"'$SITENAME'"}}]' 2> /dev/null | jgrep -s logical_id 2> /dev/null`
 DELMANAGED=`atomia service delete --account $ACCOUNT --service "$MANAGEDITEMID" 2> /dev/null`
-if [ "$?" != "0" ]; then 
-	Error "Could not delete managed service" 
+if [ "$?" != "0" ]; then
+	Error "Could not delete managed service"
 fi
 
 # Update the preview zone of the website service
@@ -45,12 +45,11 @@ if [ "$PREVIEWRECORDATA" != "$CLUSTERIP" ]; then
 fi
 
 MODSTATUS=`atomia service modify --account $ACCOUNT --service "$CSWEBSITEID" --servicedata '{ "properties" : { "MigrationStatus" : ""}}' 2> /dev/null`
-if [ "$?" != "0" ]; then 
-	Error "Could not update migration status" 
+if [ "$?" != "0" ]; then
+	Error "Could not update migration status"
 fi
 
 restatemachine_transition_to "stop"
 restatemachine_transition_after_seconds 0
 restatemachine_status_message "Migration rolled back"
 exit 0
-
